.PHONY: clean All

All:
	@echo "----------Building project:[ aaah - Debug ]----------"
	@cd "aaah" && $(MAKE) -f  "aaah.mk"
clean:
	@echo "----------Cleaning project:[ aaah - Debug ]----------"
	@cd "aaah" && $(MAKE) -f  "aaah.mk" clean
