.PHONY: clean All

All:
	@echo "----------Building project:[ F_TimeBomb - Debug ]----------"
	@cd "F_TimeBomb" && $(MAKE) -f  "F_TimeBomb.mk"
clean:
	@echo "----------Cleaning project:[ F_TimeBomb - Debug ]----------"
	@cd "F_TimeBomb" && $(MAKE) -f  "F_TimeBomb.mk" clean
